name: Erotic Stories
favicon: null
layout_spectrum: 0.7904469405766577
typography_spectrum: 0.6742470599710941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7666812289971858
  lightness: 0.38724177284166217
  saturation: 0.10392862395383418
  rhythmicContrast: 0.921389466850087
purpose: []
